name: PR Comment # Write a comment in the PR with a link to the preview of the given website
on:
  pull_request:
    types: [opened, reopened]
jobs:
  pr_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # post comment
    steps:
      - name: Create PR comment
        # PR build, NOT from a fork, and NOT from Dependabot (no preview is deployed for those)
        if: github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name && github.event.pull_request.user.login != 'dependabot[bot]'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b
        with:
          message: 'Once the build has completed, you can preview your PR at this URL: https://${{ github.event.pull_request.base.repo.owner.login }}.github.io/${{ github.event.pull_request.base.repo.name }}/previews/PR${{ github.event.number }}/'
          github-token: ${{ secrets.GITHUB_TOKEN }}